<?php

namespace Acme\ProsalesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModesreglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModesreglementRepository extends EntityRepository
{
}
