<?php

namespace Acme\ProsalesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesRepository extends EntityRepository
{
    public function ListeVillesParPays($idpays)
    {    
        $query = $this
            ->createQueryBuilder('u')           
            ->where('u.pays=:idpays')
            ->setParameter('idpays', $idpays)
            ->orderBy('u.nom', 'ASC');
        try {
            return $query;
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }    
}
