<?php

namespace Proxies\__CG__\Acme\ProsalesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Organisations extends \Acme\ProsalesBundle\Entity\Organisations implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'id', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'nom', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'adresse', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'tel', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'fax', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'email', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'web', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'description', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'createdAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'updatedAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'contact', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'devis', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'commande', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'ville', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'referent', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'statut', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'organisationsliees', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'organisationliee', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'action');
        }

        return array('__isInitialized__', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'id', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'nom', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'adresse', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'tel', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'fax', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'email', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'web', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'description', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'createdAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'updatedAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'contact', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'devis', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'commande', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'ville', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'referent', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'statut', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'organisationsliees', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'organisationliee', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Organisations' . "\0" . 'action');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Organisations $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeb($web)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeb', array($web));

        return parent::setWeb($web);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeb', array());

        return parent::getWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\Acme\ProsalesBundle\Entity\Contacts $contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', array($contact));

        return parent::addContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\Acme\ProsalesBundle\Entity\Contacts $contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', array($contact));

        return parent::removeContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function addDevi(\Acme\ProsalesBundle\Entity\Devis $devis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDevi', array($devis));

        return parent::addDevi($devis);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDevi(\Acme\ProsalesBundle\Entity\Devis $devis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDevi', array($devis));

        return parent::removeDevi($devis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevis', array());

        return parent::getDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\Acme\ProsalesBundle\Entity\Commandes $commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', array($commande));

        return parent::addCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\Acme\ProsalesBundle\Entity\Commandes $commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', array($commande));

        return parent::removeCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommande', array());

        return parent::getCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(\Acme\ProsalesBundle\Entity\Villes $ville = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferent(\Acme\ProsalesBundle\Entity\Referents $referent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferent', array($referent));

        return parent::setReferent($referent);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferent', array());

        return parent::getReferent();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(\Acme\ProsalesBundle\Entity\Statuts $statut = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', array($statut));

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getListecontacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListecontacts', array());

        return parent::getListecontacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getListedevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListedevis', array());

        return parent::getListedevis();
    }

    /**
     * {@inheritDoc}
     */
    public function getListecommandes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListecommandes', array());

        return parent::getListecommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function getListeactions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListeactions', array());

        return parent::getListeactions();
    }

    /**
     * {@inheritDoc}
     */
    public function doStuffOnPostUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'doStuffOnPostUpdate', array());

        return parent::doStuffOnPostUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function doStuffOnPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'doStuffOnPreUpdate', array());

        return parent::doStuffOnPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrganisationsliee(\Acme\ProsalesBundle\Entity\Organisations $organisationsliees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrganisationsliee', array($organisationsliees));

        return parent::addOrganisationsliee($organisationsliees);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrganisationsliee(\Acme\ProsalesBundle\Entity\Organisations $organisationsliees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrganisationsliee', array($organisationsliees));

        return parent::removeOrganisationsliee($organisationsliees);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisationsliees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisationsliees', array());

        return parent::getOrganisationsliees();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrganisationliee(\Acme\ProsalesBundle\Entity\Organisations $organisationliee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrganisationliee', array($organisationliee));

        return parent::addOrganisationliee($organisationliee);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrganisationliee(\Acme\ProsalesBundle\Entity\Organisations $organisationliee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrganisationliee', array($organisationliee));

        return parent::removeOrganisationliee($organisationliee);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisationliee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisationliee', array());

        return parent::getOrganisationliee();
    }

    /**
     * {@inheritDoc}
     */
    public function addAction(\Acme\ProsalesBundle\Entity\Actions $action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAction', array($action));

        return parent::addAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAction(\Acme\ProsalesBundle\Entity\Actions $action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAction', array($action));

        return parent::removeAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', array());

        return parent::getAction();
    }

}
