<?php

namespace Proxies\__CG__\Acme\ProsalesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contacts extends \Acme\ProsalesBundle\Entity\Contacts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'id', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'nom', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'prenom', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'email', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'fixe', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'fax', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'mobile', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'adresse', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'observation', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'createdAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'updatedAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'connectedAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'civilite', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'ville', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'saisipar', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'organisation', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'service', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'centresinteret');
        }

        return array('__isInitialized__', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'id', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'nom', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'prenom', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'email', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'fixe', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'fax', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'mobile', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'adresse', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'observation', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'createdAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'updatedAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'connectedAt', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'civilite', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'ville', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'saisipar', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'organisation', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'service', '' . "\0" . 'Acme\\ProsalesBundle\\Entity\\Contacts' . "\0" . 'centresinteret');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contacts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFixe($fixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixe', array($fixe));

        return parent::setFixe($fixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFixe', array());

        return parent::getFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation($observation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', array($observation));

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', array());

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setConnectedAt($connectedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConnectedAt', array($connectedAt));

        return parent::setConnectedAt($connectedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectedAt', array());

        return parent::getConnectedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCivilite(\Acme\ProsalesBundle\Entity\Civilites $civilite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivilite', array($civilite));

        return parent::setCivilite($civilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivilite', array());

        return parent::getCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(\Acme\ProsalesBundle\Entity\Villes $ville = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaisipar(\Acme\ProsalesBundle\Entity\Referents $saisipar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaisipar', array($saisipar));

        return parent::setSaisipar($saisipar);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaisipar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaisipar', array());

        return parent::getSaisipar();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganisation(\Acme\ProsalesBundle\Entity\Organisations $organisation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganisation', array($organisation));

        return parent::setOrganisation($organisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisation', array());

        return parent::getOrganisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setService(\Acme\ProsalesBundle\Entity\Services $service = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', array($service));

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', array());

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function addCentresinteret(\Acme\ProsalesBundle\Entity\Centresinteret $centresinteret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCentresinteret', array($centresinteret));

        return parent::addCentresinteret($centresinteret);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCentresinteret(\Acme\ProsalesBundle\Entity\Centresinteret $centresinteret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCentresinteret', array($centresinteret));

        return parent::removeCentresinteret($centresinteret);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentresinteret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentresinteret', array());

        return parent::getCentresinteret();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayContacts', array());

        return parent::getArrayContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getListecentresinteret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListecentresinteret', array());

        return parent::getListecentresinteret();
    }

}
