acme_prosales:
    resource: "@AcmeProsalesBundle/Resources/config/routing.yml"
    prefix:   /

_prosales_login:
    pattern:   /login
    defaults:  { _controller: AcmeProsalesBundle:Secured:login }
    
_security_check:
    pattern:   /login_check    
    
_prosales_logout:
    pattern:   /logout
    defaults:  { _controller: AcmeProsalesBundle:Default:logout } 