security:
    encoders:
        Acme\ProsalesBundle\Entity\Referents:
            algorithm:        sha512
            encode_as_base64: true
            iterations:       5000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AcmeProsalesBundle:Referents, property: username }
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: _prosales_login
                csrf_provider: form.csrf_provider
            logout:
                path:   _prosales_logout
                target: _welcome_prosales


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }