Acme\ProsalesBundle\Entity\Lignesdevis:
  type: entity
  repositoryClass: Acme\ProsalesBundle\Entity\Repository\LignesdevisRepository      
  table: prosales_lignesdevis
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    ordre:
      type: integer   
    reference:
      type: string
      length: 100
    prixht:
      type: decimal
      precision: 10
      scale: 2   
    quantite:
      type: integer  
    remise:
      type: decimal
      precision: 10
      scale: 2
    totalht:
      type: decimal
      precision: 10
      scale: 2    
    description:
      type: text
      nullable: true      
  manyToOne:
    devis:
      targetEntity: Devis
      inversedBy: lignesdevis
      joinColumn:
        name: devis_id
        referencedColumnName: id      