Acme\ProsalesBundle\Entity\Modesreglement:
  type: entity
  repositoryClass: Acme\ProsalesBundle\Entity\Repository\ModesreglementRepository      
  table: prosales_modesreglement
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    type:
      type: string
      length: 255
  lifecycleCallbacks: {  }    