Acme\ProsalesBundle\Entity\Modelescourriers:
  type: entity
  repositoryClass: Acme\ProsalesBundle\Entity\Repository\ModelescourriersRepository      
  table: prosales_modelescourriers
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    libelle:
      type: string
      length: 100
    sujet:
      type: string
      length: 150      
    description:
      type: text
      nullable: true      
  lifecycleCallbacks: {  }    