Acme\ProsalesBundle\Entity\Pays:
  type: entity
  repositoryClass: Acme\ProsalesBundle\Entity\Repository\PaysRepository   
  table: prosales_pays
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nom:
      type: string
      length: 100 
  oneToMany:
    villes:
      targetEntity:  Villes
      mappedBy: pays      
  lifecycleCallbacks: {  }