Acme\ProsalesBundle\Entity\Services:
  type: entity
  repositoryClass: Acme\ProsalesBundle\Entity\Repository\ServicesRepository   
  table: prosales_services
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nom:
      type: string
      length: 100  
  lifecycleCallbacks: {  }