devis:
    pattern:  /
    defaults: { _controller: "AcmeProsalesBundle:Devis:index" }

devis_show:
    pattern:  /{id}/show
    defaults: { _controller: "AcmeProsalesBundle:Devis:show" }

devis_new:
    pattern:  /new
    defaults: { _controller: "AcmeProsalesBundle:Devis:new" }

devis_create:
    pattern:  /create
    defaults: { _controller: "AcmeProsalesBundle:Devis:create" }
    requirements: { _method: post }

devis_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeProsalesBundle:Devis:edit" }

devis_update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmeProsalesBundle:Devis:update" }
    requirements: { _method: post|put }

devis_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeProsalesBundle:Devis:delete" }
    requirements: { _method: post|delete }
