modelescourriers:
    path:     /
    defaults: { _controller: "AcmeProsalesBundle:Modelescourriers:index" }

modelescourriers_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeProsalesBundle:Modelescourriers:show" }

modelescourriers_new:
    path:     /new
    defaults: { _controller: "AcmeProsalesBundle:Modelescourriers:new" }

modelescourriers_create:
    path:     /create
    defaults: { _controller: "AcmeProsalesBundle:Modelescourriers:create" }
    requirements: { _method: post }

modelescourriers_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeProsalesBundle:Modelescourriers:edit" }

modelescourriers_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeProsalesBundle:Modelescourriers:update" }
    requirements: { _method: post|put }

modelescourriers_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeProsalesBundle:Modelescourriers:delete" }
    requirements: { _method: post|delete }
