referents:
    pattern:  /
    defaults: { _controller: "AcmeProsalesBundle:Referents:index" }

referents_show:
    pattern:  /{id}/show
    defaults: { _controller: "AcmeProsalesBundle:Referents:show" }

referents_new:
    pattern:  /new
    defaults: { _controller: "AcmeProsalesBundle:Referents:new" }

referents_create:
    pattern:  /create
    defaults: { _controller: "AcmeProsalesBundle:Referents:create" }
    requirements: { _method: post }

referents_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeProsalesBundle:Referents:edit" }

referents_update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmeProsalesBundle:Referents:update" }
    requirements: { _method: post|put }

referents_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeProsalesBundle:Referents:delete" }
    requirements: { _method: post|delete }
